repos:
-   repo: local
    hooks:
    -   id: compile_pip_requirements
        name: compile pip requirements
        language: system
        entry: >
            /usr/bin/bazel run //extlibs:nanopb_requirements.update;
            /usr/bin/bazel run //software/thunderscope:requirements.update;
            /usr/bin/bazel run //software/jetson_nano/ansible:requirements.update;
            /usr/bin/bazel run //software/simulated_tests:requirements.update;

    -   id: fix_formatting
        name: fix common trivial code errors
        language: system
        entry: formatting_scripts/fix_formatting.sh 

    -   id: generate_fsm_diagrams
        name: generate new FSM diagrams
        language: python
        entry: ./src/software/ai/fsm_diagram_generator.py
