repos:
-   repo: local
    hooks:
    -   id: compile_pip_requirements
        name: compile pip requirements
        language: system
        entry: formatting_scripts/compile_pip_requirements.sh

    -   id: fix_formatting
        name: fix common trivial code errors
        language: system
        entry: formatting_scripts/fix_formatting.sh 

    -   id: generate_fsm_diagrams
        name: generate new FSM diagrams
        language: python
        entry: formatting_scripts/fsm_diagram_generator.py
